version: '3'
services:
  nextcloud-db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - ./nextcloud-db:/var/lib/postgresql/data
    env_file:
      - ./.env
  # nextcloud:
  # pihole:
  # plex:
